// Auth Action Types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const SET_LOGGED_PROFILE = "SET_LOGGED_PROFILE";
export const LOGOUT = "LOGOUT";

// Home Action Types
export const FETCH_STAFF_BEGIN = "FETCH_STAFF_BEGIN";
export const FETCH_STAFF_SUCCESS = "FETCH_STAFF_SUCCESS";
export const FETCH_STAFF_FAILURE = "FETCH_STAFF_FAILURE";
export const FETCH_IMMOBILI_BEGIN = "FETCH_IMMOBILI_BEGIN";
export const FETCH_IMMOBILI_SUCCESS = "FETCH_IMMOBILI_SUCCESS";
export const FETCH_IMMOBILI_FAILURE = "FETCH_IMMOBILI_FAILURE";
export const SET_TERMINI_DI_RICERCA = "SET_TERMINI_DI_RICERCA";

// Cerca Casa Action Types
export const FETCH_RICERCA_IMMOBILI_BEGIN = "FETCH_RICERCA_IMMOBILI_BEGIN";
export const FETCH_RICERCA_IMMOBILI_SUCCESS = "FETCH_RICERCA_IMMOBILI_SUCCESS";
export const FETCH_RICERCA_IMMOBILI_FAILURE = "FETCH_RICERCA_IMMOBILI_FAILURE";

// Dettaglio Immobile Action Types
export const GET_IMMOBILE_DETAILS_REQUEST = "GET_IMMOBILE_DETAILS_REQUEST";
export const GET_IMMOBILE_DETAILS_SUCCESS = "GET_IMMOBILE_DETAILS_SUCCESS";
export const GET_IMMOBILE_DETAILS_FAIL = "GET_IMMOBILE_DETAILS_FAIL";

// Gestione Immobili Action Types
export const GET_IMMOBILI_REQUEST = "GET_IMMOBILI_REQUEST";
export const GET_IMMOBILI_SUCCESS = "GET_IMMOBILI_SUCCESS";
export const GET_IMMOBILI_FAILURE = "GET_IMMOBILI_FAILURE";
export const DELETE_IMMOBILE_REQUEST = "DELETE_IMMOBILE_REQUEST";
export const DELETE_IMMOBILE_SUCCESS = "DELETE_IMMOBILE_SUCCESS";
export const DELETE_IMMOBILE_FAILURE = "DELETE_IMMOBILE_FAILURE";
export const UPDATE_IMMOBILE_REQUEST = "UPDATE_IMMOBILE_REQUEST";
export const UPDATE_IMMOBILE_SUCCESS = "UPDATE_IMMOBILE_SUCCESS";
export const UPDATE_IMMOBILE_FAILURE = "UPDATE_IMMOBILE_FAILURE";
export const FETCH_STAFF_REQUEST = "FETCH_STAFF_REQUEST";
export const FETCH_STAFF_FAIL = "FETCH_STAFF_FAIL";

// Gestione Utenti Action Types
export const FETCH_UTENTI_REQUEST = "FETCH_UTENTI_REQUEST";
export const FETCH_UTENTI_SUCCESS = "FETCH_UTENTI_SUCCESS";
export const FETCH_UTENTI_FAILURE = "FETCH_UTENTI_FAILURE";
export const DELETE_UTENTE_REQUEST = "DELETE_UTENTE_REQUEST";
export const DELETE_UTENTE_SUCCESS = "DELETE_UTENTE_SUCCESS";
export const DELETE_UTENTE_FAILURE = "DELETE_UTENTE_FAILURE";
export const FETCH_DETTAGLI_UTENTE_REQUEST = "FETCH_DETTAGLI_UTENTE_REQUEST";
export const FETCH_DETTAGLI_UTENTE_SUCCESS = "FETCH_DETTAGLI_UTENTE_SUCCESS";
export const FETCH_DETTAGLI_UTENTE_FAILURE = "FETCH_DETTAGLI_UTENTE_FAILURE";
export const MODIFICA_UTENTE_REQUEST = "MODIFICA_UTENTE_REQUEST";
export const MODIFICA_UTENTE_SUCCESS = "MODIFICA_UTENTE_SUCCESS";
export const MODIFICA_UTENTE_FAILURE = "MODIFICA_UTENTE_FAILURE";
export const CARICA_RUOLI_REQUEST = "CARICA_RUOLI_REQUEST";
export const CARICA_RUOLI_SUCCESS = "CARICA_RUOLI_SUCCESS";
export const CARICA_RUOLI_FAILURE = "CARICA_RUOLI_FAILURE";
export const CREA_UTENTE_REQUEST = "CREA_UTENTE_REQUEST";
export const CREA_UTENTE_SUCCESS = "CREA_UTENTE_SUCCESS";
export const CREA_UTENTE_FAILURE = "CREA_UTENTE_FAILURE";

// Gestione Valutazioni Action Types
export const FETCH_VALUTAZIONI_REQUEST = "FETCH_VALUTAZIONI_REQUEST";
export const FETCH_VALUTAZIONI_SUCCESS = "FETCH_VALUTAZIONI_SUCCESS";
export const FETCH_VALUTAZIONI_FAILURE = "FETCH_VALUTAZIONI_FAILURE";
export const DELETE_VALUTAZIONE_REQUEST = "DELETE_VALUTAZIONE_REQUEST";
export const DELETE_VALUTAZIONE_SUCCESS = "DELETE_VALUTAZIONE_SUCCESS";
export const DELETE_VALUTAZIONE_FAILURE = "DELETE_VALUTAZIONE_FAILURE";
export const FETCH_VALUTAZIONE_DETTAGLI_REQUEST = "FETCH_VALUTAZIONE_DETTAGLI_REQUEST";
export const FETCH_VALUTAZIONE_DETTAGLI_SUCCESS = "FETCH_VALUTAZIONE_DETTAGLI_SUCCESS";
export const FETCH_VALUTAZIONE_DETTAGLI_FAILURE = "FETCH_VALUTAZIONE_DETTAGLI_FAILURE";
export const TOGGLE_ATTIVO_REQUEST = "TOGGLE_ATTIVO_REQUEST";
export const TOGGLE_ATTIVO_SUCCESS = "TOGGLE_ATTIVO_SUCCESS";
export const TOGGLE_ATTIVO_FAILURE = "TOGGLE_ATTIVO_FAILURE";

// Vendi Casa Action Types
export const CREATE_VALUTAZIONE_REQUEST = "CREATE_VALUTAZIONE_REQUEST";
export const CREATE_VALUTAZIONE_SUCCESS = "CREATE_VALUTAZIONE_SUCCESS";
export const CREATE_VALUTAZIONE_FAILURE = "CREATE_VALUTAZIONE_FAILURE";
